### ISSUE TITLE
OSVR Gitter?

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-General#1]
Should we have a public Gitter room setup for OSVR?

**Comment by rpavlik** [comment]
Considered it, but right now just sticking with the mailing list. If that gets high enough traffic that we need something interactive, we'll reconsider.

cc @yboger

**Comment by gching** [comment]
@rpavlik looks like this is done :+1:

**Comment by rpavlik** [comment]
Right-o!
