### ISSUE TITLE
OSVR Stingray

### ISSUE THREAD

**Issue by Edozie101** [OSVR/OSVR-General#3]
Any word on when a Stingray integration repo will be created or how I can start to help build it out?

**Comment by VRguy** [comment]
We would love to help you get started. Do you have info on how Stingray can be extended to support other HMDs/tracking systems? Do they have an API for such extensions?

**Comment by Edozie101** [comment]
I am in contact with Autodesk Developer relations right now asking for those features. Currently you can read http://help.autodesk.com/view/Stingray/ENU/?guid=__developer_writing_plugins_design_html for writing plugin designs.

**Comment by Edozie101** [comment]
I'll let you know of any updates

**Comment by VRguy** [comment]
It seems that with some source code access, this can be done. The core OSVR team will be happy to help you with the process, even though we can't dedicate someone at the moment to do it.

**Comment by Edozie101** [comment]
If we form some closed team we can have access to the source code of stingray for the purpose of OSVR integration. We will just have to find a group of people who are interested in doing it. 

Also, would integrating the Open VR SDK from Valve, work with OSVR headsets, has that been tested yet ?

**Comment by rpavlik** [comment]
There is an "alpha-level" driver providing some access to OSVR devices through Valve's SDK, however, their SDK is less general and has a less expressive device and system model. If you want OSVR integration, the best way is to just integrate OSVR itself: the SteamVR/OpenVR driver is essentially a "shim" to permit existing apps on that SDK to run on a wider range of equipment.

**Comment by Edozie101** [comment]
Ok thanks for the info , any news on how I can form a group to work on OSVR Stingray integration ?

**Comment by VRguy** [comment]
We can form a private Github repository until it is ready for a broader 
audience. We can then invite interested parties to participate.

Does that work for you?

**Comment by rpavlik** [comment]
Repo was created, IIRC, but there was not much progress made and I'm pretty sure this engine is defunct now. Not sure if there's any reason why it couldn't be opened, but I also don't know if it would be useful to anyone - I never had access to the Stingray engine so I don't know the status.

Closing - re-open if there's no contractual/NDA reason to keep the repo closed and if there would be a benefit to opening it up, and I can see if we can get that opened.
