### ISSUE TITLE
OSVR Boxstarter Boost 404

### ISSUE THREAD

**Issue by somecodemonkey** [OSVR/OSVR-General#5]
Not sure where this belongs but the catch all seemed appropriate. When trying to install using the latest OSVR-Boxstarter-0.2-63-g68579fd-DEV.exe I get errors when the program tries to install boost, stating there's a 404 error when trying to fetch the boost_64 and boost_86 libraries from sourceforge. Therefore not installing boost libs and causing CMake to fail when trying to generate. I managed to remedy this by downloading the latest boost, building and appending the include and lib directories to CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH respectively in CMakeLists.txt.

**Comment by rpavlik** [comment]
Sorry for the delay in reply. I think we've de-emphasized the boxstarter stuff in our docs, since it's really better just for setting up demo machines or dev vms from scratch but that's not a common thing to do once you are not giving CES demos. :D Closing.
