### ISSUE TITLE
Access permission for OSVR Wiki

### ISSUE THREAD

**Issue by agirault** [OSVR/OSVR-General#7]
While looking into the first wiki I found [1], I had trouble finding the Linux build documentation [2], which I found through a Google search. I thought I could do my first contribution in OSVR by improving the doc. When doing so, I actually discovered I was able to edit the Wiki myself [3].

[1] https://github.com/OSVR/OSVR-General/wiki/HDK-Unboxing-and-Getting-Started
[2] https://github.com/OSVR/OSVR-Core/wiki/Linux-Build-Instructions
[3] https://github.com/OSVR/OSVR-General/wiki/HDK-Unboxing-and-Getting-Started/_compare/a3e4345b48dfce7629ba3fa42af1934c5fb92a5f...ee5152df415066dae372622e3f6ac910b283c050

I am not sure that a fork/MR system exists for Wiki's on GitHub, but I wanted to bring this up in case this is not the behavior you were expecting for the wiki. I doubt anybody would have fun deleting everything, but you never know : https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by waldyrious** [comment]
That's exactly how wikis are supposed to work, and github wikis are no exception. They are git repositories too, but separate from the main repo. Even if someone deleted everything, restoring the previous state would be as simple as a `git revert`. I actually think it's a pity that more systems aren't as open as wikis, and that people find the open model surprising.

**Comment by rpavlik** [comment]
Sorry for the delay in reply. Thank you for your contributions! We can make these harder to contribute to but will only do so if non-constructive contributions (eg spam, etc) become a problem.
